### ISSUE TITLE
I'd make sure this doesn't provide a security problem, like exposing the key (remember that YAP keys are unrestricted).

### ISSUE THREAD

**Issue by LittleGreenViper** [pjaudiomv/apikey-checker#1]

**Comment by LittleGreenViper** [comment]
I'm closing the issue, but figgered I'd leave it there.

**Comment by pjaudiomv** [comment]
wow just saw this, good point. I'll check to make sure that it doesn't.

**Comment by LittleGreenViper** [comment]
Sorry. I opened and closed it, figuring you would get a notification. Maybe I should have left it open.

**Comment by pjaudiomv** [comment]
I think its good, as it just uses a query string get request for key, I don't see a way you could extract a key from it. the user will expose it from the javascript maps test, but they are the ones with the key testing it.

**Comment by LittleGreenViper** [comment]
Might want to add a note of caution, then.

**Comment by pjaudiomv** [comment]
cool added the caution, alternatively I could include a config file that the key gets entered into and make the javascript check optional this would limit exposure to only those using the javascript map api checker portion.
